# -*- coding: utf-8 -*-
# Android Logging Tool
# This tool help tester analyse Android Logging
# Version : beta


from PyQt5 import QtCore, QtWidgets


class FilterWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 575)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 332, 423))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.horizontalLayout_2.addWidget(self.timeEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Filter Window"))
        self.label.setText(_translate("Dialog", "Date"))
        self.label_2.setText(_translate("Dialog", "Timestamp"))
        self.label_3.setText(_translate("Dialog", "Process    "))
        self.label_4.setText(_translate("Dialog", "Thread     "))
        self.label_5.setText(_translate("Dialog", "Level"))
        self.comboBox.setItemText(0, _translate("Dialog", "Choose"))
        self.comboBox.setItemText(1, _translate("Dialog", "Verbose"))
        self.comboBox.setItemText(2, _translate("Dialog", "Debug"))
        self.comboBox.setItemText(3, _translate("Dialog", "Info"))
        self.comboBox.setItemText(4, _translate("Dialog", "Warning"))
        self.comboBox.setItemText(5, _translate("Dialog", "Error"))
        self.label_6.setText(_translate("Dialog", "Module    "))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Null"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "AAR"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Account"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "CBZ"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "CCS"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "CEN"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "DAT"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "Data Purchase"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "Demo Mode"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "Disclaimer"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "EA"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "ECALL"))
        self.comboBox_2.setItemText(12, _translate("Dialog", "ECU Swap"))
        self.comboBox_2.setItemText(13, _translate("Dialog", "E-Manual"))
        self.comboBox_2.setItemText(14, _translate("Dialog", "EV"))
        self.comboBox_2.setItemText(15, _translate("Dialog", "Feedback"))
        self.comboBox_2.setItemText(16, _translate("Dialog", "Finance/ Credit"))
        self.comboBox_2.setItemText(17, _translate("Dialog", "Himalaya"))
        self.comboBox_2.setItemText(18, _translate("Dialog", "IOT"))
        self.comboBox_2.setItemText(19, _translate("Dialog", "IPPT"))
        self.comboBox_2.setItemText(20, _translate("Dialog", "Lidget 2.0"))
        self.comboBox_2.setItemText(21, _translate("Dialog", "LHI"))
        self.comboBox_2.setItemText(22, _translate("Dialog", "MMOTA"))
        self.comboBox_2.setItemText(23, _translate("Dialog", "OSB"))
        self.comboBox_2.setItemText(24, _translate("Dialog", "PAAK"))
        self.comboBox_2.setItemText(25, _translate("Dialog", "Payment"))
        self.comboBox_2.setItemText(26, _translate("Dialog", "Provisioning"))
        self.comboBox_2.setItemText(27, _translate("Dialog", "RCC"))
        self.comboBox_2.setItemText(28, _translate("Dialog", "Relax mode"))
        self.comboBox_2.setItemText(29, _translate("Dialog", "Remote control"))
        self.comboBox_2.setItemText(30, _translate("Dialog", "RNR"))
        self.comboBox_2.setItemText(31, _translate("Dialog", "RSA"))
        self.comboBox_2.setItemText(32, _translate("Dialog", "Smart Scene"))
        self.comboBox_2.setItemText(33, _translate("Dialog", "Smart Wellness"))
        self.comboBox_2.setItemText(34, _translate("Dialog", "User Privacy"))
        self.comboBox_2.setItemText(35, _translate("Dialog", "VA"))
        self.comboBox_2.setItemText(36, _translate("Dialog", "VHA"))
        self.comboBox_2.setItemText(37, _translate("Dialog", "VPA"))
        self.comboBox_2.setItemText(38, _translate("Dialog", "V2I"))
        self.comboBox_2.setItemText(39, _translate("Dialog", "WFHS"))
        self.comboBox_2.setItemText(40, _translate("Dialog", "WIR"))
        self.label_7.setText(_translate("Dialog", "Message "))
        self.pushButton.setText(_translate("Dialog", "Apply"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
